version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=ROOT_PASSWORD
    volumes:
      - ./data:/data/db
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
      - "27017:27017"
